name: CI
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: NPM Install
      run: npm ci 
    - name: NPM BUILD
      run: npm run build --if-present
      env:
        CI: false
    - name: copy files to server 
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "./dist/"
        target: "/var/www/vilo" 